"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, ArrowRight, MapPin, Truck } from "lucide-react";
import { useCart } from "@/components/cart-provider";
import { formatVnd } from "@/lib/types";

export default function CheckoutPage() {
  const router=useRouter();const {lines,ready,subtotal,clear}=useCart();
  const [method,setMethod]=useState<"SHIP"|"PICKUP">("SHIP");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  const [name,setName]=useState("");const [phone,setPhone]=useState("");const [email,setEmail]=useState("");const [street,setStreet]=useState("");const [ward,setWard]=useState("");const [district,setDistrict]=useState("");const [city,setCity]=useState("Hà Nội");
  const shippingFee=0;
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");if(!lines.length){setError("Giỏ hàng đang trống.");return}setBusy(true);try{const response=await fetch("/api/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({customerName:name,phone,email,fulfillmentMethod:method,shippingAddress:method==="SHIP"?{full_name:name,phone,street,ward,district,city}:null,items:lines.map(l=>({product_id:l.product.id,size:l.size,color:l.color,quantity:l.quantity}))})});const result=await response.json();if(!response.ok)throw new Error(result.error??"Không thể tạo đơn hàng.");clear();router.push(`/track/${result.tracking_token}`)}catch(e){setError(e instanceof Error?e.message:"Đã xảy ra lỗi. Vui lòng thử lại.");setBusy(false)}}
  if(!ready)return <main className="page-shell"><div className="empty-state">Đang tải checkout…</div></main>;
  if(!lines.length)return <main className="page-shell"><div className="cart-empty"><h2>Giỏ hàng đang trống.</h2><Link href="/products" className="button-dark">Xem sneakers <ArrowRight size={15}/></Link></div></main>;
  return <main className="page-shell"><div className="page-title-row"><div><span className="section-kicker">DSEB / Secure your pair</span><h1>CHECKOUT.</h1></div><Link href="/cart" className="text-link"><ArrowLeft size={14}/> Quay lại giỏ hàng</Link></div><form className="checkout-layout" onSubmit={submit}><div><section className="form-card"><h2>Thông tin khách hàng</h2><div className="form-grid"><div className="field"><label>HỌ VÀ TÊN</label><input required autoComplete="name" value={name} onChange={e=>setName(e.target.value)} placeholder="Nguyễn Văn An"/></div><div className="field"><label>SỐ ĐIỆN THOẠI</label><input required autoComplete="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="0912 345 678"/></div><div className="field full"><label>EMAIL</label><input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="ban@email.com"/></div></div></section>
    <section className="form-card"><h2>Nhận hàng</h2><div className="fulfillment-choice"><button type="button" className={`choice-card ${method==="SHIP"?"selected":""}`} onClick={()=>setMethod("SHIP")}><Truck size={20}/><span>Giao tận nơi<small>COD · Miễn phí vận chuyển</small></span></button><button type="button" className={`choice-card ${method==="PICKUP"?"selected":""}`} onClick={()=>setMethod("PICKUP")}><MapPin size={20}/><span>Nhận tại cửa hàng<small>Miễn phí · DSEB Flagship</small></span></button></div>
      {method==="SHIP"?<div className="form-grid"><div className="field full"><label>ĐỊA CHỈ ĐƯỜNG</label><input required autoComplete="street-address" value={street} onChange={e=>setStreet(e.target.value)} placeholder="Số nhà, tên đường"/></div><div className="field"><label>PHƯỜNG / XÃ</label><input required value={ward} onChange={e=>setWard(e.target.value)} placeholder="Phường"/></div><div className="field"><label>QUẬN / HUYỆN</label><input required value={district} onChange={e=>setDistrict(e.target.value)} placeholder="Quận"/></div><div className="field full"><label>TỈNH / THÀNH PHỐ</label><input required value={city} onChange={e=>setCity(e.target.value)} placeholder="Hà Nội"/></div></div>:<div className="pickup-callout"><strong>DSEB Flagship Store</strong><br/>National Economics University<br/>207 Giải Phóng, Hà Nội<br/><span className="inventory-note">Thanh toán COD tại thời điểm nhận hàng.</span></div>}
    </section><section className="form-card"><h2>Thanh toán</h2><div className="choice-card selected"><span className="payment-cod">COD</span><span>Thanh toán khi nhận hàng<small>Chỉ thanh toán tiền mặt khi nhận đơn.</small></span></div></section>{error&&<div className="error-banner">{error}</div>}</div>
    <aside className="summary-card"><h2>Đơn hàng của bạn</h2>{lines.map((l,i)=><div className="summary-row" key={`${l.product.id}-${i}`}><span>{l.quantity} × {l.product.name}<br/><small>Size {l.size}</small></span><span>{formatVnd(Number(l.product.price)*l.quantity)}</span></div>)}<div className="summary-row"><span>Tạm tính</span><span>{formatVnd(subtotal)}</span></div><div className="summary-row"><span>Giao hàng</span><span>{shippingFee?formatVnd(shippingFee):"Miễn phí"}</span></div><div className="summary-row total"><span>Tổng COD</span><span>{formatVnd(subtotal+shippingFee)}</span></div><button className="button-dark" disabled={busy}>{busy?"ĐANG TẠO ĐƠN…":"XÁC NHẬN ĐẶT HÀNG"}<ArrowRight size={16}/></button><p className="inventory-note">Hàng được giữ trong kho sau khi đặt đơn. Doanh thu chỉ ghi nhận sau khi bạn xác nhận đã nhận hàng.</p></aside></form></main>;
}
