"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight,ShieldCheck } from "lucide-react";
import { createBrowserClient } from "@supabase/ssr";

export default function LoginPage(){const router=useRouter();const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key){setError("Thiếu cấu hình Supabase. Hãy điền erp/.env.local rồi khởi động lại.");setBusy(false);return}
    const supabase=createBrowserClient(url,key);const {error:loginError}=await supabase.auth.signInWithPassword({email,password});if(loginError){setError("Email hoặc mật khẩu chưa chính xác.");setBusy(false);return}const {data:isAdmin,error:roleError}=await supabase.rpc("is_erp_admin");if(roleError||!isAdmin){await supabase.auth.signOut();setError("Tài khoản này chưa được cấp quyền ERP trong public.erp_admins.");setBusy(false);return}router.replace("/dashboard");router.refresh()}
  return <main className="login-screen"><section><div className="login-brand">DSEB<span>Move business forward.</span></div><p className="login-copy">Một workspace rõ ràng cho đơn hàng, vận hành và dòng chảy tồn kho — cùng một nguồn dữ liệu với DSEB Store.</p></section><form className="login-card" onSubmit={submit}><span className="section-kicker"><ShieldCheck size={13}/> Secure administrator access</span><h1>Welcome back.</h1><p>Đăng nhập để vào DSEB Operations.</p><div className="field"><label>EMAIL</label><input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="admin@dseb-demo.com"/></div><div className="field"><label>PASSWORD</label><input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Nhập mật khẩu"/></div>{error&&<div className="error-banner">{error}</div>}<button className="button-primary" disabled={busy}>{busy?"ĐANG ĐĂNG NHẬP…":"ĐĂNG NHẬP"}<ArrowRight size={15}/></button><p className="inventory-note" style={{marginTop:18}}>Chỉ người dùng được thêm vào danh sách ERP admin mới có thể đăng nhập.</p></form></main>;
}
